In [1]:
import numpy as np
#建立3個學生,5個分數
scores = np.random.randint(50,101,size=(3,5))
scores

array([[ 71,  72,  73,  66,  62],
       [ 93,  99,  91,  58, 100],
       [ 60,  69,  73, 100,  91]])

In [3]:
#numpy 統計
np.sum(scores[0])  #加總
np.average(scores[1])  #平均

88.2

In [4]:
for i in scores:
    print(i)

[71 72 73 66 62]
[ 93  99  91  58 100]
[ 60  69  73 100  91]


In [5]:
scores.dtype

dtype('int64')

In [8]:
#使用DataFrame呈現表格
import pandas as pd

df = pd.DataFrame(data=scores,index=['張婕筠','王XX','陳XX'],columns=['國文','英文','數學','地理','歷史'])
df

國文  英文  數學   地理   歷史
張婕筠  71  72  73   66   62
王XX  93  99  91   58  100
陳XX  60  69  73  100   91

In [9]:
df.values

array([[ 71,  72,  73,  66,  62],
       [ 93,  99,  91,  58, 100],
       [ 60,  69,  73, 100,  91]])