In [2]:
import random
random.randint(50,100)

66

In [6]:
import numpy as np
#建立50個學生,5個分數
scores = np.random.randint(50,101,size=(50,5))
scores

array([[ 81,  53,  60,  97, 100],
       [ 52,  70,  80,  53,  77],
       [ 57,  88,  57,  90,  50],
       [ 87,  57,  54,  80,  69],
       [ 79,  69,  89,  80,  63],
       [ 99,  68,  76,  52,  59],
       [ 62,  78,  69,  70,  76],
       [ 79,  90,  95,  88,  88],
       [ 57,  88,  61,  91,  61],
       [ 71,  93,  68,  59,  95],
       [ 56,  84,  81,  62,  54],
       [ 59,  77,  58,  98,  63],
       [ 98,  95,  83,  74,  62],
       [ 66,  61,  87,  91,  74],
       [ 95,  55,  69,  88,  66],
       [ 94,  95,  50,  57,  62],
       [ 60,  66,  85,  61,  80],
       [ 81,  61,  97,  75,  77],
       [ 98,  58,  77,  92,  80],
       [ 70,  80,  79,  87,  50],
       [ 92,  51,  91,  71,  55],
       [ 87,  85,  58,  95,  57],
       [ 96,  58,  85,  52,  57],
       [ 55,  98,  90, 100,  83],
       [ 51,  61,  57,  72,  71],
       [ 51,  58,  51,  75,  96],
       [ 91,  56,  89,  93,  52],
       [ 91,  91,  96,  63,  77],
       [ 69,  79,  51,  70,  56],
       [ 75,  

In [7]:
#抓1個人分數
scores[0]

array([ 81,  53,  60,  97, 100])

In [8]:
#抓3個人分數
scores[0:3]

array([[ 81,  53,  60,  97, 100],
       [ 52,  70,  80,  53,  77],
       [ 57,  88,  57,  90,  50]])

In [10]:
#抓每個人第一個分數
scores[0:30,0]

array([81, 52, 57, 87, 79, 99, 62, 79, 57, 71, 56, 59, 98, 66, 95, 94, 60,
       81, 98, 70, 92, 87, 96, 55, 51, 51, 91, 91, 69, 75])